services:
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: docker/fpm/Dockerfile
    volumes:
      - .:/var/www
      - /var/www/vendor
      - ./logs:/var/www/logs
    networks:
      - app-network
        
  db:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - 6432:${DB_PORT:-5432} # 6432 - основная БД
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/db/init:/docker-entrypoint-initdb.d # накатывания схемы db только при первом создании volume
    env_file: .env

  db_test:
    image: postgres:latest
    restart: always
    container_name: postgres_test
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: test_db
    ports:
      - "6543:5432"  # 6543 - база для тестов 
    networks:
      - app-network
    volumes:
      - db_test_data:/var/lib/postgresql/data
      - ./docker/db/init:/docker-entrypoint-initdb.d # init-скрипты для тестовой базы

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  db_data:
  db_test_data:

networks:
  app-network:
    driver: bridge