services:
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: docker/fpm/Dockerfile
    volumes:
      - .:/var/www
      - ./logs:/var/www/logs
    networks:
      - app-network
        
  db:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - 6432:${DB_PORT}
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: .env

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge