CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    token VARCHAR(255) UNIQUE NOT NULL,
    okx_api_key VARCHAR(255) NOT NULL,
    okx_secret_key VARCHAR(255) NOT NULL,
    okx_passphrase VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_balances (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    ccy VARCHAR(16) NOT NULL,
    eq NUMERIC(36, 18) NOT NULL,
    eq_usd NUMERIC(36, 2) NOT NULL,
    rate NUMERIC(36, 10),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, ccy)
);