CREATE TABLE IF NOT EXISTS wallet_balances (
    id SERIAL PRIMARY KEY,
    ccy VARCHAR(16) NOT NULL,
    eq NUMERIC(36, 18) NOT NULL,
    eq_usd NUMERIC(36, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);