name: Test and Deploy to VDS

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Run PHPUnit tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: test_db
        ports:
          - 6543:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pdo_pgsql

      - name: Install dependencies
        run: composer install --no-interaction --no-scripts

      - name: Wait for PostgreSQL
        run: sleep 10

      - name: Apply test DB schema
        run: |
          psql -h localhost -p 6543 -U test_user -d test_db -f ./docker/db/init/schema.sql
        env:
          PGPASSWORD: secret

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit --configuration phpunit.xml


  deploy:
    name: Deploy to VDS
    runs-on: ubuntu-latest
    needs: test  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 195.133.194.43
          username: root
          key: ${{ secrets.VDS_SSH_KEY }}
          script: |
            cd /root/investor-portfolio
            git reset --hard
            git pull origin main

            docker compose down
            docker compose up -d --build