name: Test and Deploy to VDS

on:
  workflow_dispatch:  # запускается вручную

jobs:
  test:
    name: Run PHPUnit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pdo_pgsql

      - name: Install dependencies
        run: composer install --no-interaction --no-scripts

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit --configuration phpunit.xml

  deploy:
    name: Deploy to VDS
    runs-on: ubuntu-latest
    needs: test  # запускать только если тесты прошли

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 195.133.194.43
          username: root
          key: ${{ secrets.VDS_SSH_KEY }}
          script: |
            cd /root/investor-portfolio
            git reset --hard
            git pull origin main

            docker compose down
            docker compose up -d --build